data = {
    "accomodate, accomodation": ["accommodate, accommodation", "two c's, two m's"],
    "acheive": ["achieve", "i before e"],
    "accross": ["across", "one c"],
    "agressive, agression": ["aggressive, aggression", "two g's"],
    "apparantly": ["apparently", "-ent not -ant"],
    "appearence": ["appearance", "ends with -ance"],
    "arguement": ["argument", "no e after the u"],
    "assasination": ["assassination", "two double s’s"],
    "basicly": ["basically", "ends with -ally"],
    "begining": ["beginning", "double n before the -ing"],
    "beleive, belive": ["believe", "i before e"],
    "bizzare": ["bizarre", "one z, double r"],
    "buisness": ["business", "begins with busi-"],
    "calender": ["calendar", "-ar not -er"],
    "Carribean": ["Caribbean", "one r, two b's"],
    "cemetary": ["cemetery", "ends with -ery"],
    "chauffer": ["chauffeur", "ends with -eur"],
    "collegue": ["colleague", "-ea- in the middle"],
    "comming": ["coming", "one m"],
    "commitee": ["committee", "double m, double t, double e"],
    "completly": ["completely", "ends with -ely"],
    "concious": ["conscious", "-sc- in the middle"],
    "curiousity": ["curiosity", "-os- in the middle"],
    "definately": ["definitely", "-ite- not -ate-"],
    "dilemna": ["dilemma", "-mm- not -mn-"],
    "dissapear": ["disappear", "one s, two p's"],
    "dissapoint": ["disappoint", "one s, two p's"],
    "ecstacy": ["ecstasy", "ends with -sy"],
    "embarass": ["embarrass", "two r's, two s’s"],
    "enviroment": ["environment", "n before the m"],
    "existance": ["existence", "ends with -ence"],
    "Farenheit": ["Fahrenheit", "begins with Fahr-"],
    "familar": ["familiar", "ends with -iar"],
    "finaly": ["finally", "two ls"],
    "florescent": ["fluorescent", "begins with fluor-"],
    "foriegn": ["foreign", "e before i"],
    "forseeable": ["foreseeable", "begins with fore-"],
    "fourty": ["forty", "begins with for-"],
    "foward": ["forward", "begins with for-"],
    "freind": ["friend", "i before e"],
    "futher": ["further", "begins with fur-"],
    "jist": ["gist", "begins with g-"],
    "glamourous": ["glamorous", "-mor- in the middle"],
    "goverment": ["government", "n before the m"],
    "gaurd": ["guard", "begins with gua-"],
    "happend": ["happened", "ends with -ened"],
    "harrass, harrassment": ["harass, harassment", "one r, two s’s"],
    "honourary": ["honorary", "-nor- in the middle"],
    "humourous": ["humorous", "-mor- in the middle"],
    "idiosyncracy": ["idiosyncrasy", "ends with -asy"],
    "immediatly": ["immediately", "ends with -ely"],
    "incidently": ["incidentally", "ends with -ally"],
    "independant": ["independent", "ends with -ent"],
    "interupt": ["interrupt", "two r's"],
    "irresistable": ["irresistible", "ends with -ible"],
    "knowlege": ["knowledge", "remember the d"],
    "liase, liason": ["liaise, liaison", "remember the second i: liais-"],
    "lollypop": ["lollipop", "i in the middle"],
    "millenium, millenia": ["millennium, millennia", "double l, double n"],
    "neccessary": ["necessary", "one c, two s’s"],
    "noticable": ["noticeable", "remember the middle e"],
    "ocassion, occassion": ["occasion", "two c's, one s"],
    "occured, occuring": ["occurred, occurring", "two c's, two r's"],
    "occurance, occurence": ["occurrence", "two c's, two r's, -ence not -ance"],
    "pavillion": ["pavilion", "one l"],
    "persistant": ["persistent", "ends with -ent"],
    "pharoah": ["pharaoh", "ends with -aoh"],
    "peice": ["piece", "i before e"],
    "politican": ["politician", "ends with -cian"],
    "Portugese": ["Portuguese", "ends with -guese"],
    "posession": ["possession", "two s’s in the middle and two at the end"],
    "prefered, prefering": ["preferred, preferring", "two r's"],
    "propoganda": ["propaganda", "begins with propa-"],
    "publically": ["publicly", "ends with -cly"],
    "realy": ["really", "two ls"],
    "recieve": ["receive", "i before e, except after c"],
    "refered, refering": ["referred, referring", "two r's"],
    "religous": ["religious", "ends with -gious"],
    "rember, remeber": ["remember", "-mem- in the middle"],
    "resistence": ["resistance", "ends with -ance"],
    "sence": ["sense", "ends with -se"],
    "seperate": ["separate", "-par- in the middle"],
    "seige": ["siege", "i before e"],
    "succesful": ["successful", "two c's, two s’s"],
    "supercede": ["supersede", "ends with -sede"],
    "suprise": ["surprise", "begins with sur-"],
    "tatoo": ["tattoo", "two t's, two o's"],
    "tendancy": ["tendency", "ends with -ency"],
    "therefor": ["therefore", "ends with -fore"],
    "threshhold": ["threshold", "one h in the middle"],
    "tommorow, tommorrow": ["tomorrow", "one m, two rs"],
    "tounge": ["tongue", "begins with ton-, ends with -gue"],
    "truely": ["truly", "no e"],
    "unforseen": ["unforeseen", "remember the e after the r"],
    "unfortunatly": ["unfortunately", "ends with -ely"],
    "untill": ["until", "one l at the end"],
    "wierd": ["weird", "e before i"],
    "whereever": ["wherever", "one e in the middle"],
    "wich": ["which", "begins with wh-"]
}